# Generated by Django 5.0.6 on 2024-07-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadobuxef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]