# Generated by Django 3.2.25 on 2024-07-10 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estadobuxef', '0002_alter_funcionario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
