# Generated by Django 5.0.6 on 2024-07-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadobuxef', '0005_auto_20240710_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='uploads/lugar/'),
        ),
    ]
