# Generated by Django 5.0.6 on 2024-07-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadobuxef', '0006_lugar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
