# Generated by Django 5.0.6 on 2024-07-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadobuxef', '0008_alter_lugar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='imagen',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
    ]
